Basket.create(name: "Birthday", ingredients: "Gourmet Snacks, Fruits, and Chardonay")
Basket.create(name: "Marriage", ingredients: "Gourmet Snacks, Fruits, Champagne, and Chardonay")
Basket.create(name: "Birth", ingredients: "Gourmet Snacks, Fruits, Cigars and Candy/Sweet Assortment")
Basket.create(name: "Anniversary", ingredients: "Gourmet Snacks, Fruits, and Chardonay")
Basket.create(name: "Valentine's", ingredients: "Gourmet Snacks, Fruits, Bubble Bath Bomb, Champagne and Chardonay")
User.create(id: 27, name: "Stevey", email: "steve@email.com", user_name: "steve_the_great", password_digest: "1234")
User.create(id: 27, name: "EStevey", email: "esteve@email.com", user_name: "esteve_the_great", password_digest: "1234")
User.create(id: 28, name: "Steven", email: "steven@email.com", user_name: "steven_the_great", password_digest: "1234")
Basket.create(name: "Valentine's", ingredients: "Gourmet Snacks, Fruits, Bubble Bath Bomb, Champagne and Chardonay")
Basket.create(name: "Valentine's", ingredients: "Gourmet Snacks, Fruits, Bubble Bath Bomb, Champagne and Chardonay")
Basket.create(name: "Valentine's", ingredients: "Gourmet Snacks, Fruits, Bubble Bath Bomb, Champagne and Chardonay")
