Basket.create(name: "Birthday", ingredients: "Gourmet Snacks, Fruits, and Chardonay")
Basket.create(name: "Marriage", ingredients: "Gourmet Snacks, Fruits, Champagne, and Chardonay")
Basket.create(name: "Birth", ingredients: "Gourmet Snacks, Fruits, Cigars and Candy/Sweet Assortment")
Basket.create(name: "Anniversary", ingredients: "Gourmet Snacks, Fruits, and Chardonay")
Basket.create(name: "Valentine's", ingredients: "Gourmet Snacks, Fruits, Bubble Bath Bomb, Champagne and Chardonay")